hyperparameters:
  NFOLD: 5
  truncate_last_timesteps: 4096
  num_class: 21
  batch_size: 32
  training_epochs: 30
  training_steps_per_epoch: 500
  shuffle_buffer: 1024

model:
  architecture_name: conv_mhsa
  input_shape: [500, 52]
  conv_filters: [128, 128, 256, 256, 512]
  kernel: [7, 7, 3, 7, 7]
  strides: [1, 2, 1, 2, 2]
  num_heads: 8
  d_model: 512
  dff: 512
  
augment:
  random_shift:
    backward: 32
    forward: 32

environment:
  type: colab_tpu

